### ISSUE TITLE
can't import inception_blockv2 and fr_utils

### ISSUE THREAD

**Issue by ravi02512** [akshaysharma096/Siamese-Networks#2]
getting error no matching distribution found with pip.

**Comment by njs89** [comment]
@ravi02512 just delete those two import lines. 
I managed to run the thing without it, after I encountered the same problem.

**Comment by ravi02512** [comment]
download 
Inception_blockv2 from   https://github.com/JudasDie/deeplearning.ai/blob/master/Convolutional%20Neural%20Networks/week4/FaceNet/inception_blocks_v2.py

fr_utils from 
https://github.com/JudasDie/deeplearning.ai/blob/master/Convolutional%20Neural%20Networks/week4/FaceNet/fr_utils.py

and put these scripts in repo folder that will work for sure
